name: Deploy Image to Github Container Registry 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './ComparadorMetodoPgto/'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
            
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2


      - name: 'Login to GitHub Container Registry  (puxadinho)'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u alexssantos --password-stdin

      # - name: 'Login to GitHub Container Registry' (jeto que deveria funcionar)
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and Push Docker Image
      #   env:
      #     REGISTRY: ghcr.io
      #     # OWNER: ${{ github.actor }}
      #     IMAGE_NAME: ${{ github.repository }}
      #   uses: docker/build-push-action@v4
      #   with:
      #     # context: ComparadorMetodoPgto
      #     file: ./ComparadorMetodoPgto/Dockerfile          
      #     push: true
      #     tags: |
      #       ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      #     # build-args: |
      #     #   ENVIRONMENT=production
      
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:          
      #     push: true
      #     tags: alexssantos/cm-pgto:latest


      ## !! denied: installation not allowed to Create organization package !!
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/alexssantos/comparador-metodo-pgto:latest
          docker push ghcr.io/alexssantos/comparador-metodo-pgto:latest

