name: Deploy Image to Github Container Registry 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './ComparadorMetodoPgto/'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PASS }}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/alexssantos/cm-pgto:latest
          docker push ghcr.io/alexssantos/cm-pgto:latest
