name: Deploy Image to Github Container Registry 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  USER: ${{ github.actor }} #alexssantos  
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
  REGISTRY_URL: ghcr.io/alexssantos/comparador-metodo-pgto

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './ComparadorMetodoPgto/'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

        
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date +%Y%m%d)-${GITHUB_SHA:0:7}" >> ${GITHUB_ENV}


      - name: 'Login to GitHub Container Registry'
        #docs: https://github.com/docker/login-action
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT2 }}

        
        #docs: https://github.com/docker/build-push-action
      - name: Build and push 3
        uses: docker/build-push-action@v5
        with:
          context: ./ComparadorMetodoPgto # (default {context}/Dockerfile)          
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ env.RELEASE_DATE }}

      # - name: 'Build Inventory Image'
      #   run: |
      #     docker build . --tag $REGISTRY_URL:${RELEASE_DATE}-${GITHUB_SHA:0:7}
      #     docker push $REGISTRY_URL:${RELEASE_DATE}-${GITHUB_SHA:0:7}

